package com.fisei.visitapp.app.dummy;

/**
 * Created by diegoztc on 06/02/15.
 */

public class Content {
    public static String[] title = { "Android", "iOS", "Windows Phone",
            "BlackBerry OS", "Ubuntu Phone" };
    public static String[] description = {
            "Android es un sistema operativo basado en Linux, diseñado principalmente para móviles con pantalla táctil como teléfonos inteligentes o tabletas inicialmente desarrollados por Android, Inc., que Google respaldó económicamente y más tarde compró en 2005,11 Android fue desvelado en 2007 junto la fundación del Open Handset Alliance: un consorcio de compañías de hardware, software y telecomunicaciones para avanzar en los estándares abiertos de los dispositivos móviles.12 El primer móvil con el sistema operativo Android se vendió en octubre de 2008.",
            "iOS es un sistema operativo móvil de la empresa Apple Inc. Originalmente desarrollado para el iPhone (iPhone OS), siendo después usado en dispositivos como el iPod Touch, iPad y el Apple TV. Apple, Inc. no permite la instalación de iOS en hardware de terceros. Tenía el 26% de cuota de mercado de sistemas operativos móviles vendidos en el último cuatrimestre de 2010, detrás de Google Android y Nokia Symbian.4 En mayo de 2010 en los Estados Unidos, tenía el 59% de consumo de datos móviles (incluyendo el iPod Touch y el iPad).",
            "Windows Phone es un sistema operativo móvil desarrollado por Microsoft, como sucesor de la plataforma Windows Mobile.2 A diferencia de su predecesor, está enfocado en el mercado de consumo generalista en lugar del mercado empresarial3 por lo que carece de muchas funcionalidades que proporcionaba la versión anterior. Microsoft ha decidido no hacer compatible Windows Phone con Windows Mobile por lo que las aplicaciones existentes no funcionan en Windows Phone haciendo necesario desarrollar nuevas aplicaciones. Con Windows Phone, Microsoft ofrece una nueva interfaz de usuario que integra varios servicios en el sistema operativo. Microsoft planeaba un estricto control del hardware que implementaría el sistema operativo, para evitar la fragmentación con la evolución del sistema, pero han reducido los requisitos de hardware de tal forma que puede que eso no sea posible.",
            "BlackBerry es una línea de teléfonos inteligentes (más conocidos por el anglicismo smartphones) desarrollada por la compañía canadiense BlackBerry (antes Research In Motion o RIM) que integra el servicio de correo electrónico móvil; aunque incluye las aplicaciones típicas de un smartphone: libreta de direcciones, calendario, listas de tareas, bloc de notas etc., así como capacidades de teléfono en los modelos más nuevos. Es fundamentalmente conocido por su teclado QWERTY incorporado, y por su capacidad para enviar y recibir correo electrónico de Internet accediendo a las redes de las compañías de telefonía celular que brindan este servicio. El término 'blackberry' también es de uso común para hacer referencia a cualquier teléfono celular que incorpore un teclado completo.",
            "Ubuntu Phone es un sistema operativo móvil basado en Linux. Es desarrollado por Canonical Ltd.. Presentado el 2 de enero de 2013 al público mediante un anuncio en la web de Ubuntu, culmina el proceso de Canonical de desarrollar una interfaz que pueda utilizarse en ordenadores de sobremesa, portátiles, netbooks, tablets y smartphones. Esta interfaz, Unity, se compone, a grandes rasgos, de un dock a la izquierda, una especie de panel en la parte superior y de un sistema de búsqueda que emplea lentes." };
}